tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

#brew "bat"
#brew "docker", link: false
#brew "fd"
brew "fish"
#brew "fzf"
brew "git"
#brew "go"
#brew "hugo"
#brew "mysql@5.7", restart_service: true, link: true
brew "nvm"
brew "python@3.9"
brew "starship"
brew "tldr"
brew "yarn"
#cask "alfred"
#cask "discord"
#cask "docker"
#cask "font-fira-code"
#cask "font-hack-nerd-font"
#cask "google-chrome"
#cask "iterm2"
#cask "keka"
#cask "mongodb-compass"
#cask "mysqlworkbench"
#cask "obsidian"
#cask "postman"
#cask "robo-3t"
#cask "slack"
#cask "spectacle"
#cask "spotify"
#cask "visual-studio-code"
#cask "vlc"
